[package]
name = "hecto"
version = "0.1.0"
edition = "2021"
description = "Basic text editor in Rust"
license = "MIT"
repository = "https://github.com/khandrym/hecto"
keywords = ["text editor"]
categories = ["text-editors"]

[dependencies]
crossterm = "0.23"
